logging:
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        bureau-out:
          destination: bureau
          contentType: application/json
        ajdc-out:
          destination: adjudication
          contentType: application/json
        process-result-in:
          group: processresultConsumers
          destination: processresult
          contentType: application/json