spring.application.name: kafka-streams-sample
logging:
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  
  cloud:
    stream:
      default:
        consumer:
          headerMode: raw
      kafka:
        binder:
          brokers: localhost:9092
          autoAddPartitions: true
          configuration:
            default:
              key:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            commit.interval.ms: 1000
        streams:
          binder.configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            application-result-in:
              consumer:
                application-id: application-result-count
      bindings:   
        bureau-out:
          destination: mbna.ccms.bureau
          contentType: application/json
          producer:
            partition-count: 2
        tsys-out:
          destination: mbna.ccms.tsys
          contentType: application/json
        ajdc-out:
          destination: mbna.ccms.adjudication
          contentType: application/json
        process-result-in:
          group: processresultConsumers
          destination: mbna.ccms.processresult
          contentType: application/json
        application-result-out:
          destination: mbna.ccms.applicationresult
        application-result-in:
          group: applicationresultConsumers
          destination: mbna.ccms.applicationresult
          consumer:
            use-native-encoding: true
          