server:
  port : 0
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        bureau-in:
          consumer:
            startOffset: latest
#            startOffset: earliest //Means start from where last time server start reading message. Eg: Server started process F2 and crashed at F10, then restart server will read message from F2.
          group: bureauIn
          destination: mbna.ccms.bureau
          contentType: application/json
        process-result-out:
          destination: mbna.ccms.processresult
          contentType: application/json
