server:
  port : 0
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        bureau-in:
          destination: bureau
          group: bureauConsumers
          contentType: application/json
        process-result-out:
          destination: processresult
          contentType: application/json