server:
  port : 0
spring:
  cloud:
    stream:
      binder:
        kafka:
          start-offset: earliest
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        bureau-in:
          group: bureauIn
          destination: bureau
          contentType: application/json
        process-result-out:
          destination: processresult
          contentType: application/json
          